theme: jekyll-theme-cayman
title: www.hinoshiba.com
description: hinoshibaか、ShungoKumasaka(<a href="https://hinoshiba.hatenablog.com/entry/2019/11/17/100616">芸名？</a>) として、セキュリティ/プログラマ/情シス なことしています<br>ラビットダッキング相棒はうさぎさんのぬいぐるみ(サムネ)です。<br>名前は、「はーちゃんうーちゃん」。<br>その子の夫は、クマさんの"あらい"と言います。
logo: ./img/avatar.jpg
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

# https://github.com/pages-themes/minimal
