theme: jekyll-theme-minimal
title: www.hinoshiba.com
description: test value.
logo: ./img/avatar.jpg
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]

# https://github.com/pages-themes/minimal
